# -*- coding: utf-8 -*-
"""1a Normalisation.R

#Automatically generated by Colab.

#Original file is located at
    https://colab.research.google.com/drive/1Rp_4M3juzYkj5M5FAyBpnWskd6CIuGcN
"""

library("tidyverse")
library("dplyr")
library("ggplot2")
library("tidyr")
library("readr")
library("readxl")

#IMPORT DATA
expr_RA <- read.csv("Rheumatoid Arthritis dataset before normalization.csv", row.names = 1)

expr_UC <- read.csv("Ulcerative Colitis dataset before normalization.normalization..csv", row.names = 1)

# REMOVE GENE AND SAMPLE WITH MISSING VALUES
expr_RA <- expr_RA[complete.cases(expr_RA), ]
expr_UC <- expr_UC[complete.cases(expr_UC), ]

expr_RA <- expr_RA[, colSums(is.na(expr_RA)) == 0]
expr_UC <- expr_UC[, colSums(is.na(expr_UC)) == 0]

batch_RA <- sub("_.*", "", colnames(expr_RA))
batch_RA <- factor(batch_RA)

table(batch_RA)

batch_UC <- sub("_.*", "", colnames(expr_UC))
batch_UC <- factor(batch_UC)

table(batch_UC)

#CALCULATE GROUP
group_RA <- ifelse(grepl("_Treat", colnames(expr_RA)), "RA", "Control")
group_RA <- factor(group_RA)

table(group_RA)

group_UC <- ifelse(grepl("_Treat", colnames(expr_UC)), "UC", "Control")
group_UC <- factor(group_UC)

table(group_UC)
table(group_RA)

#NORMALISATION
expr_RA_norm <- normalizeBetweenArrays(expr_RA)
expr_UC_norm <- normalizeBetweenArrays(expr_UC)

#differentially expressed analysis
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("sva")
library(sva)
mod <- model.matrix(~group_RA)

expr_RA_batch <- ComBat(
  dat = as.matrix(expr_RA_norm),
  batch = batch_RA,
  mod = mod,
  par.prior = TRUE
)

mod_UC <- model.matrix(~group_UC)
expr_UC_batch <- ComBat(
  dat = as.matrix(expr_UC_norm),
  batch = batch_UC,
  mod = mod_UC,
  par.prior = TRUE
)

expr_RA_filt <- expr_RA_batch[rowMeans(expr_RA_batch) > 1, ]
expr_UC_filt <- expr_UC_batch[rowMeans(expr_UC_batch) > 1, ]

design_RA <- model.matrix(~group_RA)

fit_RA <- lmFit(expr_RA_filt, design_RA)
fit_RA <- eBayes(fit_RA)

deg_RA <- topTable(fit_RA, coef=2, number=Inf)

design_UC <- model.matrix(~group_UC)

fit_UC <- lmFit(expr_UC_filt, design_UC)
fit_UC <- eBayes(fit_UC)

deg_UC <- topTable(fit_UC, coef=2, number=Inf)

#pvalue analysis
sig_RA <- deg_RA[deg_RA$adj.P.Val < 0.05 & abs(deg_RA$logFC) > 1, ]
nrow(sig_RA)

sig_UC <- deg_UC[deg_UC$adj.P.Val < 0.05 & abs(deg_UC$logFC) > 1, ]
nrow(sig_UC)

summary(as.vector(as.matrix(expr_RA_filt)))
summary(as.vector(as.matrix(expr_UC_filt)))
